name: Run eval (manual)

on:
  workflow_dispatch:
    inputs:
      config:
        description: "Evals configuration file to use"
        required: true
        default: "./examples/simple/simple.yml"

jobs:
  run-eval:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          token: ${{ secrets.PAT }}
          config: ${{ github.event.inputs.config }}
