name: Run eval (manual)

on:
  workflow_dispatch:
    inputs:
      config:
        description: "Evals configuration file to use"
        required: true
        default: "./simple.yml"

jobs:
  run-eval:
    runs-on: ubuntu-latest

    steps:
      - name: Run GitHub Models Evals
        uses: github/prompt-evals-wip@main
        with:
          config: ./smple.yml
